#!/bin/bash

# Generating a simple systemd service.

if [[ "$(whoami)" != "root" ]]
then
	echo "This script must run as root."
	exit 1
fi
if [[ -z "$1" || -z "$2" || -z "$3" ]]
then
	echo "Usage:"
	echo ""$0" <Name> <User> <Exec>"
	exit 1
fi

echo "Creating service:"
echo "  Name: "$1""
echo "  User: "$2""
echo "  Exec: "$3""

cat > "/etc/systemd/system/"$1".service" << [EOF]
[Unit]
Description="$1"
After=network.target
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
RestartSec=1
User="$2"
ExecStart="$3"
[Install]
WantedBy=multi-user.target
[EOF]
