#!/bin/bash

# Checking for accidental WiFi disconnects,
# and reconnecting (this script may need to run as root).

Network="" # The desired network to attempt reconnection

cd "$( dirname "$( realpath "$0" )" )"

while true
do
	ping -q -w 10 -c 1 192.168.1.1  > /dev/null && Gateway=1 || Gateway=0
	Carrier=$(cat /sys/class/net/wlp1s0/carrier)

	if [ "$Carrier" != 1 ] || [ "$Gateway" != 1 ]
	then
		sleep 20
		echo "Connection unresponsive, reconnecting"
		nmcli con down "$Network"
		nmcli con up "$Network" passwd-file WiFiReconnect.psk
		echo "Probably reconnected"
	fi
	sleep 20
done
